name: image_picker
description: Flutter plugin for selecting images from the Android and iOS image
  library, and taking new pictures with the camera.
repository: https://github.com/flutter/plugins/tree/main/packages/image_picker/image_picker
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+image_picker%22
version: 0.8.5

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: image_picker_android
      ios:
        default_package: image_picker_ios

dependencies:
  flutter:
    sdk: flutter
  image_picker_android:
    git:
      url: https://github.com/ivansemkin/plugins.git
      path: packages/image_picker/image_picker_android
      ref: ios-optional-permissions
  image_picker_ios:
    git:
      url: https://github.com/ivansemkin/plugins.git
      path: packages/image_picker/image_picker_ios
      ref: ios-optional-permissions
  image_picker_platform_interface:
    git:
      url: https://github.com/ivansemkin/plugins.git
      path: packages/image_picker/image_picker_platform_interface
      ref: ios-optional-permissions


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
  plugin_platform_interface: ^2.0.0
